version: '3.6'

services:
  app:
    tty: true
    image: rapid-checkout
    build: .
    command:
      - "yarn"
      - "start"
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
  database:
    image: bitnami/mongodb
    ports:
      - 27017:27017
    volumes:
      - /data/mongodb-persistence:/bitnami
